/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author root
 */
public class GUI extends javax.swing.JFrame {
    
    Connection koneksi;
    ResultSet cmp;
    Statement stm;
    boolean ada = false;
    boolean ubah = false;
    private Object[][] dataTable = null; //meletakan nim nama jurusan dari database ke tabel
private String[] header = {"ID Member","Nama","NickName","Tier"};


    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    buka_db();
        baca_data();
    }

    public void buka_db(){
        try{ 
            Class.forName("com.mysql.jdbc.Driver"); 
            koneksi = DriverManager.getConnection("jdbc:mysql://localhost/cmp","root","" + "");
            System.out.println("Koneksi Sukses");
        }
        catch(ClassNotFoundException e){
            System.out.println("Eror #1 : "+ e.getMessage());
            System.exit(0); 
        }
        catch(SQLException e){ 
            System.out.println("Eror #2 : "+ e.getMessage()); 
            System.exit(0); 
        } 
    }
    public void baca_data(){
        try{
            
        stm = koneksi.createStatement();
        cmp = stm.executeQuery("select * from Member"); 
        ResultSetMetaData meta = cmp.getMetaData();
        int col = meta.getColumnCount();
    int baris = 0; 
    while(cmp.next()) { 
        baris = cmp.getRow(); 
    }
    dataTable = new Object[baris][col]; 
    int x = 0; 
    cmp.beforeFirst(); 
    while(cmp.next()) 
    {
        dataTable[x][0] = cmp.getString("id_member"); 
dataTable[x][1] = cmp.getString("nama_member");
dataTable[x][2] = cmp.getString("nickname");
dataTable[x][3] = cmp.getString("tier");
x++; 
    }
     tabel.setModel(new DefaultTableModel(dataTable,header));
}catch(SQLException e){
JOptionPane.showMessageDialog(null, e); 
} 
}
    private void kosong(){
        txt1.setText("");
        txt2.setText("");
        txt4.setText("");
        txt5.setText("");
        try{
            
        stm = koneksi.createStatement();
        cmp = stm.executeQuery("select * from Member"); 
        ResultSetMetaData meta = cmp.getMetaData();
        int col = meta.getColumnCount();
    int baris = 0; 
    while(cmp.next()) { 
        baris = cmp.getRow(); 
    }
    dataTable = new Object[baris][col]; 
    int x = 0; 
    cmp.beforeFirst(); 
    while(cmp.next()) 
    {
        dataTable[x][0] = cmp.getString("id_member"); 
dataTable[x][1] = cmp.getString("nama_member");
dataTable[x][2] = cmp.getString("nickname");
dataTable[x][3] = cmp.getString("tier");
x++; 
    }
     tabel.setModel(new DefaultTableModel(dataTable,header));
}catch(SQLException e){
JOptionPane.showMessageDialog(null, e); 
} 

    }
private void field(){
    int row=tabel.getSelectedRow();
    txt1.setText((String)tabel.getValueAt(row,0));
    
    txt2.setText((String)tabel.getValueAt(row,1));
    txt4.setText((String)tabel.getValueAt(row,2));
    txt5.setText((String)tabel.getValueAt(row,3));
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        txt2 = new javax.swing.JTextField();
        txt4 = new javax.swing.JTextField();
        txt5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DATA SQUAD IMO");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lemon/Milk", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setText("Nama");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 64, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lemon/Milk", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(254, 254, 254));
        jLabel2.setText("Nickname");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 114, -1, -1));

        jLabel4.setFont(new java.awt.Font("Lemon/Milk", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(254, 254, 254));
        jLabel4.setText("Tier");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 164, -1, -1));

        tabel.setBackground(new java.awt.Color(1, 1, 1));
        tabel.setFont(new java.awt.Font("Lemon/Milk", 0, 15)); // NOI18N
        tabel.setForeground(new java.awt.Color(254, 254, 254));
        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Member", "Nama Member", "Nickname", "Jabatan"
            }
        ));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 212, 610, 150));
        getContentPane().add(txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 168, -1));
        getContentPane().add(txt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 168, -1));
        getContentPane().add(txt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 168, -1));

        jButton1.setFont(new java.awt.Font("Lemon/Milk", 0, 15)); // NOI18N
        jButton1.setText("SIMPAn");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 103, -1));

        jButton2.setFont(new java.awt.Font("Lemon/Milk", 0, 15)); // NOI18N
        jButton2.setText("TAMBAH");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 103, -1));

        jButton3.setFont(new java.awt.Font("Lemon/Milk", 0, 15)); // NOI18N
        jButton3.setText("HAPUS");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 105, -1));

        jLabel5.setFont(new java.awt.Font("Lemon/Milk", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(254, 254, 254));
        jLabel5.setText("ID Member");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 14, -1, -1));
        getContentPane().add(txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 168, -1));

        jButton4.setFont(new java.awt.Font("Lemon/Milk", 0, 15)); // NOI18N
        jButton4.setText("Batal");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 103, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/4095f31a1f0e8b43f6f5603ed697bd13.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 630, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
               int confirm = JOptionPane.showConfirmDialog(this, "Apakah anda ingin menambah data?","Konfirmasi Keluar Aplikasi",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (confirm == JOptionPane.YES_OPTION){
        try{
stm.executeUpdate("INSERT into Member VALUES('"+txt1.getText()+"','"+txt2.getText()+"','"+txt4.getText()+"','"+txt5.getText()+"')");
        JOptionPane.showMessageDialog(null, "Data telah ditambah !!!"); 
        tabel.setModel(new DefaultTableModel(dataTable,header)); 
        baca_data();
        //setTombol(true);
        kosong();
        }catch(SQLException e) { 
        JOptionPane.showMessageDialog(null, e);
        }
        } 
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        int confirm = JOptionPane.showConfirmDialog(this, "Apakah anda ingin menyimpan data?","Konfirmasi Keluar Aplikasi",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (confirm == JOptionPane.YES_OPTION){
        try{
stm.executeUpdate("update Member set id_member='"+txt1.getText()+"',nama_member='"+txt2.getText()+"',nickname='"+txt4.getText()+"',tier='"+txt5.getText()+"'");
        JOptionPane.showMessageDialog(null, "Data telah disimpan !!!"); 
        tabel.setModel(new DefaultTableModel(dataTable,header)); 
        baca_data();
        //setTombol(true);
        kosong();
        }catch(SQLException e) { 
        JOptionPane.showMessageDialog(null, e);
        }
        }
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(this, "Apakah anda ingin menghapus data?","Konfirmasi Keluar Aplikasi",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (confirm == JOptionPane.YES_OPTION) {
        try{ 
            
            stm.executeUpdate("delete from Member where id_member='"+txt1.getText()+"'");
             JOptionPane.showMessageDialog(null, "Data telah dihapus !!!"); 
            
            tabel.setModel(new DefaultTableModel(dataTable,header));
            baca_data(); 
            kosong();
        }catch(SQLException e) {
            JOptionPane.showMessageDialog(null, e); 
        }
                       }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        // TODO add your handling code here:
        field();
    }//GEN-LAST:event_tabelMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        kosong();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txt4;
    private javax.swing.JTextField txt5;
    // End of variables declaration//GEN-END:variables
}
